### ISSUE TITLE
Archive files available over IPFS?

### ISSUE THREAD

**Issue by AlexanderOMara** [internetarchive/dweb-archive#114]
I'm not sure if this is the right place to ask, but are archive files supposed to be available over IPFS? Because they don't seem to be working if they are.

For example:

1.  Navigate to this URL: https://dweb.me/archive/archive.html?identifier=xkcd_lego&download=1
2.  Uncheck all the DWeb options except IPFS
3.  Click `lego.png`

I can see in the following log in the developer console:

```
dweb-transports Fetching ipfs:/ipfs/bafybeibkjr2qoq46ol2ogeqenkrpysjn6qmsejt4ikhsvqffdjo5tumpaa via IPFS failed: No such file +8ms
```

Additionally, attempting to load that file over Cloudflare's proxy also doesn't work:

```
https://cloudflare-ipfs.com/ipfs/bafybeibkjr2qoq46ol2ogeqenkrpysjn6qmsejt4ikhsvqffdjo5tumpaa
```

I'm curious to know if it should be possible to access these files over IPFS, or if the ability to do this is in the works.

**Comment by mitra42** [comment]
The answer to this is complex, and I'd be happy to have a chat in more detail if you are trying to do something specific. 

What we do is add files to a IPFS-URLstore instance running at the archive (we call this a SuperPeer), that makes a reference from a IPFS hash to a URL on the archive, so that if someone requests that hash, it **should**, if not available elsewhere, route to the IPFS peer at the archive and fetch the file. 

BUT ... 
* The IPFS SuperPeer has had a tendency in the past to crash and lose all the references, and we've no way of knowing which it still has and forget our cache of them. 
* IPFS routing essentially doesnt work (yet) at scale, so we can't announce our hashes to the IPFS network so the cloudflare link won't work. The link will only work on a IPFS peer connecting directly to our superpeer (like the browser does), and so of course until the IPFS team figures out how to scale routing then this gives no added value unless you happen to be close enough (e.g. same LAN) to get it from a neighbour.  As far as we know it doesnt even work between two peers connected to our super peer at the same time. 
* IPFS doesnt give us an error message when its not succeeding, this is a long-standing issue that hits many projects trying to use IPFS, but doesn't seem to get any attention, for this reason in dweb.me / dweb.archive.org we only use IPFS to fetch larger files when all else fails. 

Note - there is a partial outage at archive.org at the moment, so any errors at the moment could be nothing to do with IPFS 

Happy to dig deeper if you have a particular application, we'd like to make the files more available over IPFS, and hope to increase their availability when IPFS gets more mature.
